apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "simple-web.fullname" . }}-config
  labels:
    {{- include "simple-web.labels" . | nindent 4 }}
data:
  HTTP_TIMEOUT: {{ .Values.pythonApp.timeout | quote }}
  SEARCH_QUERY: {{ .Values.pythonApp.searchQuery | quote }}
  API_URL: {{ .Values.pythonApp.apiUrl | quote }}
  FILTER_KEYWORD: {{ .Values.pythonApp.filterKeyword | quote }}